### ISSUE TITLE
Find-as-you-type (FAYT) reset with, or after, a space

### ISSUE THREAD

**Issue by grahamperrin** [maximstewart/Tab-Search-Firefox#1]
1. Visit https://addons.mozilla.org/addon/tab-search-and-manage/
2. add the extension
5. open a new window
4. click the button for the extension
5. switch to multi-window mode
6. dismiss the dialogue
7. click the button for the extension
8. type: 

<kbd>t</kbd><kbd>a</kbd><kbd>b</kbd><kbd>Space bar</kbd>

### Expected

Ability to seek a multi-word string

### Actual results

With Waterfox 56.2.3, as far as I can tell the search field is reset (cleared) with the first key press _after_ <kbd>Space bar</kbd>. 

With Firefox 62.0, the search field is reset when <kbd>Space bar</kbd> is keyed.

**Comment by maximstewart** [comment]
Hi, thank you for taking the time to help me improve the plugin by reporting your issue! I have a few questions to try and get to the bottom of this.

First, are you a Windows, Mac, or Linux user?
With the second window, is it under the first window, next to it, or minimized?
If on Linux, is the second window on a different virtual desktop?

I should preface this by say that as far as I am aware, window selection is handled by the desktop and the browser. Since the search is resetting, that mean the plugin has found what you are looking for and there is a single instance of it. So, it's trying to select the new window. I might be limited to what I can fix or do for guidance. I know on Linux Firefox doesn't seem to actually redirect the display to the virtual one it's on if a call is made to it. Otherwise, everything I asked above works. I haven't gotten to test fully on Windows since I don't use it that often and I haven't tried Mac.

**Comment by grahamperrin** [comment]
FreeBSD-CURRENT here. For an issue such as this, it's reasonable to treat Firefox (and Waterfox) on FreeBSD as you would treat them on Linux. 

Here's a screen recording of the extension with Firefox 62.0.2. In the second half of the recording there is (I think) strange behaviour when typing part of the word _review_

[2018-09-30 18:16.zip](https://github.com/maximstewart/Tab-Search-Firefox/files/2431798/2018-09-30.18.16.zip)

> … Since the search is resetting, that means the plugin has found what you are looking for and there is a single instance of it. …

It 'feels' strange that the word disappears before I can finish typing …

**Comment by maximstewart** [comment]
Hmmm, OK, looking over the video everything looks like it's working as it should up until a new window is opened. As a quick side note, when you type "itdominator" fully at 19 seconds in, it does seem to miss one of the tabs since there are actually three. But, even though it's missing one it does show the two you can select. By the way, when doing a search, if more than one tab is found, you can look through those that are found and click in the plugin window to select the tab.

OK, on to the problem actual. I see at 47 seconds in that you pop up a new window and then switch to the previous one to begin searching. I notice you don't actually click on any content of the previous window but go straight to the plugin button. What looks like what's going on is that the previous window is still selected by Firefox and when you're doing a search it registers that search to the previous window and says I have found what you want and switches. That's weird b/c in window mode, we don't expect a redirect since there are duplicates found but not in the same window.

I'd like you to go through that duplicate window test and before immediately going to the plugin please click on the content of the tab you have selected and THEN open the plugin and begin typing. Does the word stay now? So, do exactly everything you did 27 seconds in BUT when going back to your main window, click on some area of the current tab window's page content and THEN click the plugin button to search.

**Comment by maximstewart** [comment]
I believe this is resolved after I made some changes. Please test and advise after updating the plugin.

**Comment by grahamperrin** [comment]
Thanks! At a glance, the windowing issue is fixed. 

From a usability perspective, the reset – more specifically – the disappearance of the UI – feels strange. Particularly if _before a search_ there was focus in a form field in the found window. Like, I might seek 

`Babcock`

– and end up with the word `cock` in a field **and** not notice the unexpected entry.

**Comment by maximstewart** [comment]
Hmmmm, I'm sorry but I'm not following? Would you make screen cap to show what you mean? From what I understand, you are talking about the plugin window disappearing after a match that is single is found, correct? So, you find the plugin window disappearing awkward? If this is correct, then there isn't a thing I can do since the plugin window is losing focus and it fires an event to hide itself. This is part of Firefox than the actual plugin.
